// <auto-generated />
using System;
using BlazorTemplate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorTemplate.Data.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("BlazorTemplate.Data.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Name = "Work First Casualty Company",
                            WorkerCount = 0
                        },
                        new
                        {
                            CompanyId = 2,
                            Name = "Widget Company LLC",
                            WorkerCount = 0
                        },
                        new
                        {
                            CompanyId = 3,
                            Name = "Awesome Enterprises",
                            WorkerCount = 0
                        });
                });

            modelBuilder.Entity("BlazorTemplate.Data.Entities.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerId");

                    b.HasIndex("AssignedCompanyId");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            WorkerId = 1,
                            AssignedCompanyId = 1,
                            BirthDate = new DateOnly(1996, 1, 1),
                            Email = "nate@email.com",
                            FirstName = "Nate",
                            LastName = "Tripp",
                            PhoneNumber = "(555) 555-5555"
                        });
                });

            modelBuilder.Entity("BlazorTemplate.Data.Entities.Worker", b =>
                {
                    b.HasOne("BlazorTemplate.Data.Entities.Company", "AssignedCompany")
                        .WithMany("Workers")
                        .HasForeignKey("AssignedCompanyId");

                    b.Navigation("AssignedCompany");
                });

            modelBuilder.Entity("BlazorTemplate.Data.Entities.Company", b =>
                {
                    b.Navigation("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
